version: '3'
services:
  rust:
    build: ./
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "28015:28015"
      - "28015:28015/udp"
      - "28016:28016"
    volumes:
      - ./rust:/steamcmd/rust
    env_file:
        - rust.env
